### ISSUE TITLE
Disable Full screen

### ISSUE THREAD

**Issue by 6--** [PeterDamianG/BoosteroidOptimizerPlugin#1]
Hi,
Thanks for this plugin! Helps a lot!
Is there a way to stop the website from forcing us to go full screen?
Thank you!

**Comment by PeterDamianG** [comment]
Hello,

Based in boosteroid system "catch-events".
[catch-events.js](https://cloud.boosteroid.com/static/streaming/catch-events.js?version=3.7.11)

We can "manipulate" and change behavior:
![console 1](https://user-images.githubusercontent.com/43484809/154248835-915df43a-b0d7-41af-8537-d226bbde0496.jpg)
And next is replace code of line 21.
`document.body.requestFullscreen().then(() =>navigator.keyboard.lock(["KeyW", ...;`
to
`navigator.keyboard?.lock(['KeyW',...]);`
![console 2](https://user-images.githubusercontent.com/43484809/154249393-ab9d3523-45dd-4386-a3c3-58cebcaf9c97.jpg)
Refresh (F5) and run. I tried it with mir4 and it worked correctly. But dota2, have issues with edges of screen.

That is the solution I thought. Sure there are better.

I add this experimental solution to extension:
![ui extension](https://user-images.githubusercontent.com/43484809/154249972-152e6665-8319-4f59-b602-515bfa8c7050.jpg)

Best regards.

**Comment by 6--** [comment]
Thanks a lot!

its working perfect for lost ark!
